# Python (p)
aliases['pa'] = 'python app.py'
aliases['pc'] = 'pip-compile'
aliases['pci'] = 'pip install pip-tools '
aliases['pcs'] = 'pip-sync'
aliases['pcu'] = 'pip-compile --upgrade > /dev/null'
aliases['pf'] = 'pip list'
aliases['pi'] = 'pip install '
aliases['pii'] = 'pip install --upgrade pip setuptools'  # Things that won't get auto-updated
aliases['pir'] = 'pip install -r requirements.txt'
aliases['pit'] = 'pip install --upgrade pip pip-tools setuptools'  # Ditto but with pip-tools
aliases['piu'] = 'pip install --upgrade '
aliases['pl'] = 'pylint *'
aliases['pp'] = 'ipython'
aliases['pr?'] = 'pip uninstall '
aliases['prf?'] = 'pip uninstall $(pip freeze)'
aliases['pv'] = 'python -V'
aliases['pw'] = 'pip show '
aliases['py'] = 'python'

# Django (pd)
aliases['pdc'] = 'python manage.py collectstatic '
aliases['pdk'] = 'python manage.py addstatictoken '
aliases['pdm'] = 'python manage.py migrate '
aliases['pdmd'] = 'python manage.py makemigrations --dry-run '
aliases['pdmm'] = 'python manage.py makemigrations '
aliases['pdmq'] = 'python manage.py sqlmigrate '
aliases['pdmw'] = 'python manage.py showmigrations '
aliases['pdp'] = 'python manage.py '
aliases['pdq'] = 'python manage.py dbshell'
aliases['pdr'] = 'python manage.py runserver_plus'
aliases['pdrm'] = 'python manage.py runserver'
aliases['pds'] = 'python manage.py shell_plus --print-sql --quiet-load'
aliases['pdsm'] = 'python manage.py shell_plus'
aliases['pdw'] = 'python -W ignore manage.py '

# Testing (pt, pdt)
aliases['pdt'] = 'python manage.py test --keepdb --exe --verbosity=3 --with-id '
aliases['pdtf'] = 'pdt --failed'
aliases['pdtn'] = 'python manage.py test --keepdb --verbosity=3 '  # without nose

# JavaScript (e)
def es_lint(args):
    if ![./node_modules/.bin/eslint @(args)]:
        print("\n${GREENBOLD}  No errors${NOCOLOR}\n")
aliases['el'] = es_lint
aliases['et'] = 'rake jasmine:ci'
aliases['etb'] = 'rake jasmine'  # in-browser

# NodeJS (en)
aliases['eni'] = 'npm install '
aliases['enr'] = 'npm start '

# PyCharm (oc)
aliases['oc'] = '/snap/bin/pycharm-professional'
aliases['ocp'] = 'oc $(bop)'  # open copied text
# function ocs {
#   # Open a series of files generated by running silversearcher
#   oc $(eval "${@} -l")  # Need to use eval so that any aliases in ${@} get parsed correctly
# }
