#!/usr/bin/env python
""" Check that the commit message is acceptable """
import sys


def check_length():
    """ Check that the commit message is long enough """
    filename = sys.argv[1]
    other = 0
    with open(filename, 'r') as fn:
        # Add the length of all lines that aren't commented out
        fn.seek(0)
        file_length = sum(len(line.strip()) for line in fn if not line.startswith('#'))
        
    # If this length is too short, reject the commit message
    # If the file length is 0, git will abort the commit, so don't bother to reject
    if file_length > 0 and file_length < 10:
        print('Commit message is too short. Please enter a longer commit message.')
        exit(1)


if __name__ == '__main__':
    check_length()
