#!/usr/bin/env python
""" Check that the commit message is acceptable """
import sys

from hook_helpers import ignore_or_exit


def check_length():
    """ Check that the commit message is long enough """
    filename = sys.argv[1]
    with open(filename, 'rt') as fn:
        # Add the length of all lines that aren't commented out
        fn.seek(0)
        file_length = sum(len(line.strip()) for line in fn if not line.startswith('#'))
        
    # If this length is too short, reject the commit message
    # If the file length is 0, git will abort the commit, so don't bother to reject
    if 0 < file_length < 10:
        print('Commit message is too short. Please enter a longer commit message.')
        ignore_or_exit()


def check_capitalization():
    """ Check that the commit message starts with a capital letter """
    filename = sys.argv[1]
    with open(filename, 'rt') as fn:
        fn.seek(0)
        first_char = fn.readline()[0]
    if first_char.islower():
        print('Commit message begins with a lowercase letter (' + first_char
              + '). Please begin your commit message with an uppercase letter.')
        ignore_or_exit()


if __name__ == '__main__':
    check_length()
    check_capitalization()
